//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodPandaDBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDelivery
    {
        public int DeliveryID { get; set; }
        public int OrderID { get; set; }
        public string DeliveryStatus { get; set; }
        public System.DateTime DeliveryTime { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
