//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodPandaDBMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int PaymentID { get; set; }
        public int UserID { get; set; }
        public int OrderID { get; set; }
        public int PaymentMethodID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblPaymentMethodType tblPaymentMethodType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
